services:
  node:
    image: node:20
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
    stdin_open: true
    command: /bin/bash
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - CHOCKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true