create schema if not exists "pm";

create table "pm"."projects" (
    "project_id" bigint generated by default as identity not null,
    "project_name" text not null,
    "project_number" text,
    "project_status" text not null default 'Quoting'::text,
    "designer_id" bigint,
    "est_framing_start" date,
    "scope" text,
    "number_units" integer,
    "job_site_id" bigint,
    "builder_id" bigint,
    "material_customer_id" bigint,
    "customer_id" bigint,
    "supplier_id" bigint,
    "supplier_contact_id" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "pm"."projects" enable row level security;

CREATE UNIQUE INDEX projects_pkey ON pm.projects USING btree (project_id);

CREATE UNIQUE INDEX projects_project_number_key ON pm.projects USING btree (project_number);

alter table "pm"."projects" add constraint "projects_pkey" PRIMARY KEY using index "projects_pkey";

alter table "pm"."projects" add constraint "projects_builder_id_fkey" FOREIGN KEY (builder_id) REFERENCES crm.customers(customer_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "pm"."projects" validate constraint "projects_builder_id_fkey";

alter table "pm"."projects" add constraint "projects_customer_id_fkey" FOREIGN KEY (customer_id) REFERENCES crm.customers(customer_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "pm"."projects" validate constraint "projects_customer_id_fkey";

alter table "pm"."projects" add constraint "projects_designer_id_fkey" FOREIGN KEY (designer_id) REFERENCES hr.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "pm"."projects" validate constraint "projects_designer_id_fkey";

alter table "pm"."projects" add constraint "projects_job_site_id_fkey" FOREIGN KEY (job_site_id) REFERENCES crm.job_sites(job_site_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "pm"."projects" validate constraint "projects_job_site_id_fkey";

alter table "pm"."projects" add constraint "projects_material_customer_id_fkey" FOREIGN KEY (material_customer_id) REFERENCES crm.customers(customer_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "pm"."projects" validate constraint "projects_material_customer_id_fkey";

alter table "pm"."projects" add constraint "projects_project_number_key" UNIQUE using index "projects_project_number_key";

alter table "pm"."projects" add constraint "projects_supplier_contact_id_fkey" FOREIGN KEY (supplier_contact_id) REFERENCES crm.contacts(contact_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "pm"."projects" validate constraint "projects_supplier_contact_id_fkey";

alter table "pm"."projects" add constraint "projects_supplier_id_fkey" FOREIGN KEY (supplier_id) REFERENCES crm.suppliers(supplier_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "pm"."projects" validate constraint "projects_supplier_id_fkey";