create schema if not exists "prod";

create table "prod"."floor_stack_trackers" (
    "floor_stack_tracker_id" bigint generated by default as identity not null,
    "stack_id" bigint not null,
    "employee_one_id" bigint,
    "employee_two_id" bigint,
    "production_date" date not null default CURRENT_DATE,
    "time_to_build" real,
    "quality_checks_performed" boolean,
    "created_at" timestamp with time zone not null default now()
);


alter table "prod"."floor_stack_trackers" enable row level security;

create table "prod"."work_stations" (
    "work_station_id" bigint generated by default as identity not null,
    "work_station_name" text not null,
    "number_operators" smallint not null,
    "is_idle" boolean,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "prod"."work_stations" enable row level security;

CREATE UNIQUE INDEX work_stations_pkey ON prod.work_stations USING btree (work_station_id);

alter table "prod"."work_stations" add constraint "work_stations_pkey" PRIMARY KEY using index "work_stations_pkey";

create table "prod"."production_lines" (
    "production_line_id" bigint generated by default as identity not null,
    "line_name" text not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "prod"."production_lines" enable row level security;

CREATE UNIQUE INDEX production_lines_pkey ON prod.production_lines USING btree (production_line_id);

alter table "prod"."production_lines" add constraint "production_lines_pkey" PRIMARY KEY using index "production_lines_pkey";

create table "prod"."production_line_stations" (
    "production_line_id" bigint not null,
    "work_station_id" bigint not null,
    "sequence_number" integer not null
);


alter table "prod"."production_line_stations" enable row level security;

create table "prod"."production_queue" (
    "production_queue_id" bigint generated by default as identity not null,
    "work_order_id" bigint,
    "stack_id" bigint,
    "status" text not null default 'Queued'::text,
    "sequence_number" integer
);


alter table "prod"."production_queue" enable row level security;

create table "prod"."production_trackers" (
    "production_tracker_id" bigint generated by default as identity not null,
    "work_station_id" bigint,
    "panel_id" bigint not null,
    "employee_one_id" bigint,
    "employee_two_id" bigint,
    "notes" text,
    "start_time" timestamp with time zone not null default now(),
    "end_time" timestamp with time zone,
    "duration" bigint
);


alter table "prod"."production_trackers" enable row level security;

create table "prod"."roof_stack_trackers" (
    "roof_stack_tracker_id" bigint generated by default as identity not null,
    "stack_id" bigint not null,
    "employee_one_id" bigint,
    "employee_two_id" bigint,
    "production_date" date not null default CURRENT_DATE,
    "time_to_build" real,
    "quality_checks_performed" boolean,
    "created_at" timestamp with time zone not null default now()
);


alter table "prod"."roof_stack_trackers" enable row level security;

create table "prod"."wall_stack_trackers" (
    "wall_stack_tracker_id" bigint generated by default as identity not null,
    "stack_id" bigint not null,
    "employee_one_id" bigint,
    "employee_two_id" bigint,
    "production_date" date not null default CURRENT_DATE,
    "time_to_build" real,
    "quality_checks_performed" boolean,
    "created_at" timestamp with time zone not null default now()
);


alter table "prod"."wall_stack_trackers" enable row level security;

create table "prod"."work_station_assignments" (
    "work_station_assignment_id" bigint generated by default as identity not null,
    "employee_id" bigint not null,
    "work_station_id" bigint not null,
    "start_time" timestamp with time zone not null default now(),
    "end_time" timestamp with time zone
);


alter table "prod"."work_station_assignments" enable row level security;

CREATE UNIQUE INDEX floor_stack_trackers_pkey ON prod.floor_stack_trackers USING btree (floor_stack_tracker_id);

CREATE UNIQUE INDEX production_line_stations_pkey ON prod.production_line_stations USING btree (production_line_id, work_station_id);

CREATE UNIQUE INDEX production_queue_pkey ON prod.production_queue USING btree (production_queue_id);

CREATE UNIQUE INDEX production_trackers_pkey ON prod.production_trackers USING btree (production_tracker_id);

CREATE UNIQUE INDEX roof_stack_trackers_pkey ON prod.roof_stack_trackers USING btree (roof_stack_tracker_id);

CREATE UNIQUE INDEX wall_stack_trackers_pkey ON prod.wall_stack_trackers USING btree (wall_stack_tracker_id);

CREATE UNIQUE INDEX work_station_assignments_pkey ON prod.work_station_assignments USING btree (work_station_assignment_id);

alter table "prod"."floor_stack_trackers" add constraint "floor_stack_trackers_pkey" PRIMARY KEY using index "floor_stack_trackers_pkey";

alter table "prod"."production_line_stations" add constraint "production_line_stations_pkey" PRIMARY KEY using index "production_line_stations_pkey";

alter table "prod"."production_queue" add constraint "production_queue_pkey" PRIMARY KEY using index "production_queue_pkey";

alter table "prod"."production_trackers" add constraint "production_trackers_pkey" PRIMARY KEY using index "production_trackers_pkey";

alter table "prod"."roof_stack_trackers" add constraint "roof_stack_trackers_pkey" PRIMARY KEY using index "roof_stack_trackers_pkey";

alter table "prod"."wall_stack_trackers" add constraint "wall_stack_trackers_pkey" PRIMARY KEY using index "wall_stack_trackers_pkey";

alter table "prod"."work_station_assignments" add constraint "work_station_assignments_pkey" PRIMARY KEY using index "work_station_assignments_pkey";

alter table "prod"."floor_stack_trackers" add constraint "floor_stack_trackers_employee_one_id_fkey" FOREIGN KEY (employee_one_id) REFERENCES hr.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "prod"."floor_stack_trackers" validate constraint "floor_stack_trackers_employee_one_id_fkey";

alter table "prod"."floor_stack_trackers" add constraint "floor_stack_trackers_employee_two_id_fkey" FOREIGN KEY (employee_two_id) REFERENCES hr.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "prod"."floor_stack_trackers" validate constraint "floor_stack_trackers_employee_two_id_fkey";

alter table "prod"."floor_stack_trackers" add constraint "floor_stack_trackers_stack_id_fkey" FOREIGN KEY (stack_id) REFERENCES pm.stacks(stack_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "prod"."floor_stack_trackers" validate constraint "floor_stack_trackers_stack_id_fkey";

alter table "prod"."production_line_stations" add constraint "production_line_stations_production_line_id_fkey" FOREIGN KEY (production_line_id) REFERENCES prod.production_lines(production_line_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "prod"."production_line_stations" validate constraint "production_line_stations_production_line_id_fkey";

alter table "prod"."production_line_stations" add constraint "production_line_stations_work_station_id_fkey" FOREIGN KEY (work_station_id) REFERENCES prod.work_stations(work_station_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "prod"."production_line_stations" validate constraint "production_line_stations_work_station_id_fkey";

alter table "prod"."production_queue" add constraint "production_queue_stack_id_fkey" FOREIGN KEY (stack_id) REFERENCES pm.stacks(stack_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "prod"."production_queue" validate constraint "production_queue_stack_id_fkey";

alter table "prod"."production_queue" add constraint "production_queue_work_order_id_fkey" FOREIGN KEY (work_order_id) REFERENCES pm.work_orders(work_order_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "prod"."production_queue" validate constraint "production_queue_work_order_id_fkey";

alter table "prod"."production_trackers" add constraint "production_trackers_employee_one_id_fkey" FOREIGN KEY (employee_one_id) REFERENCES hr.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "prod"."production_trackers" validate constraint "production_trackers_employee_one_id_fkey";

alter table "prod"."production_trackers" add constraint "production_trackers_employee_two_id_fkey" FOREIGN KEY (employee_two_id) REFERENCES hr.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "prod"."production_trackers" validate constraint "production_trackers_employee_two_id_fkey";

alter table "prod"."production_trackers" add constraint "production_trackers_panel_id_fkey" FOREIGN KEY (panel_id) REFERENCES pm.panels(panel_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "prod"."production_trackers" validate constraint "production_trackers_panel_id_fkey";

alter table "prod"."production_trackers" add constraint "production_trackers_work_station_id_fkey" FOREIGN KEY (work_station_id) REFERENCES prod.work_stations(work_station_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "prod"."production_trackers" validate constraint "production_trackers_work_station_id_fkey";

alter table "prod"."roof_stack_trackers" add constraint "roof_stack_trackers_employee_one_id_fkey" FOREIGN KEY (employee_one_id) REFERENCES hr.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "prod"."roof_stack_trackers" validate constraint "roof_stack_trackers_employee_one_id_fkey";

alter table "prod"."roof_stack_trackers" add constraint "roof_stack_trackers_employee_two_id_fkey" FOREIGN KEY (employee_two_id) REFERENCES hr.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "prod"."roof_stack_trackers" validate constraint "roof_stack_trackers_employee_two_id_fkey";

alter table "prod"."roof_stack_trackers" add constraint "roof_stack_trackers_stack_id_fkey" FOREIGN KEY (stack_id) REFERENCES pm.stacks(stack_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "prod"."roof_stack_trackers" validate constraint "roof_stack_trackers_stack_id_fkey";

alter table "prod"."wall_stack_trackers" add constraint "wall_stack_trackers_employee_one_id_fkey" FOREIGN KEY (employee_one_id) REFERENCES hr.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "prod"."wall_stack_trackers" validate constraint "wall_stack_trackers_employee_one_id_fkey";

alter table "prod"."wall_stack_trackers" add constraint "wall_stack_trackers_employee_two_id_fkey" FOREIGN KEY (employee_two_id) REFERENCES hr.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "prod"."wall_stack_trackers" validate constraint "wall_stack_trackers_employee_two_id_fkey";

alter table "prod"."wall_stack_trackers" add constraint "wall_stack_trackers_stack_id_fkey" FOREIGN KEY (stack_id) REFERENCES pm.stacks(stack_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "prod"."wall_stack_trackers" validate constraint "wall_stack_trackers_stack_id_fkey";

alter table "prod"."work_station_assignments" add constraint "work_station_assignments_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES hr.employees(employee_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "prod"."work_station_assignments" validate constraint "work_station_assignments_employee_id_fkey";

alter table "prod"."work_station_assignments" add constraint "work_station_assignments_work_station_id_fkey" FOREIGN KEY (work_station_id) REFERENCES prod.work_stations(work_station_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "prod"."work_station_assignments" validate constraint "work_station_assignments_work_station_id_fkey";