create table "hr"."timesheets" (
    "timesheet_id" bigint generated by default as identity not null,
    "employee_id" bigint not null,
    "pay_period_id" character varying,
    "status" text not null,
    "approver_id" bigint,
    "approver_name" text,
    "approved_on" date,
    "note" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "hr"."timesheets" enable row level security;

CREATE UNIQUE INDEX timesheets_pkey ON hr.timesheets USING btree (timesheet_id);

alter table "hr"."timesheets" add constraint "timesheets_pkey" PRIMARY KEY using index "timesheets_pkey";

alter table "hr"."timesheets" add constraint "timesheets_approver_id_fkey" FOREIGN KEY (approver_id) REFERENCES hr.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "hr"."timesheets" validate constraint "timesheets_approver_id_fkey";

alter table "hr"."timesheets" add constraint "timesheets_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES hr.employees(employee_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "hr"."timesheets" validate constraint "timesheets_employee_id_fkey";

alter table "hr"."timesheets" add constraint "timesheets_pay_period_id_fkey" FOREIGN KEY (pay_period_id) REFERENCES hr.pay_periods(pay_period_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "hr"."timesheets" validate constraint "timesheets_pay_period_id_fkey";