create table "hr"."timesheet_entries" (
    "timesheet_entry_id" bigint generated by default as identity not null,
    "timesheet_id" bigint,
    "project_id" bigint,
    "timesheet_task_id" bigint,
    "entry_date" date,
    "time_in" timestamp with time zone not null default now(),
    "time_out" timestamp with time zone,
    "duration" bigint,
    "minutes_paid" bigint,
    "minutes_banked" bigint,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "hr"."timesheet_entries" enable row level security;

CREATE UNIQUE INDEX timesheet_entries_pkey ON hr.timesheet_entries USING btree (timesheet_entry_id);

alter table "hr"."timesheet_entries" add constraint "timesheet_entries_pkey" PRIMARY KEY using index "timesheet_entries_pkey";

alter table "hr"."timesheet_entries" add constraint "timesheet_entries_project_id_fkey" FOREIGN KEY (project_id) REFERENCES pm.projects(project_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "hr"."timesheet_entries" validate constraint "timesheet_entries_project_id_fkey";

alter table "hr"."timesheet_entries" add constraint "timesheet_entries_timesheet_id_fkey" FOREIGN KEY (timesheet_id) REFERENCES hr.timesheets(timesheet_id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "hr"."timesheet_entries" validate constraint "timesheet_entries_timesheet_id_fkey";

alter table "hr"."timesheet_entries" add constraint "timesheet_entries_timesheet_task_id_fkey" FOREIGN KEY (timesheet_task_id) REFERENCES hr.timesheet_tasks(timesheet_task_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "hr"."timesheet_entries" validate constraint "timesheet_entries_timesheet_task_id_fkey";

create table "hr"."payrolls" (
    "payroll_id" bigint generated by default as identity not null,
    "employee_id" bigint,
    "pay_period_id" character varying,
    "processor_id" bigint,
    "processor_name" text,
    "processed_on" date,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "hr"."payrolls" enable row level security;

CREATE UNIQUE INDEX payrolls_pkey ON hr.payrolls USING btree (payroll_id);

alter table "hr"."payrolls" add constraint "payrolls_pkey" PRIMARY KEY using index "payrolls_pkey";

alter table "hr"."payrolls" add constraint "payrolls_employee_id_fkey" FOREIGN KEY (employee_id) REFERENCES hr.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "hr"."payrolls" validate constraint "payrolls_employee_id_fkey";

alter table "hr"."payrolls" add constraint "payrolls_pay_period_id_fkey" FOREIGN KEY (pay_period_id) REFERENCES hr.pay_periods(pay_period_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "hr"."payrolls" validate constraint "payrolls_pay_period_id_fkey";

alter table "hr"."payrolls" add constraint "payrolls_processor_id_fkey" FOREIGN KEY (processor_id) REFERENCES hr.employees(employee_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "hr"."payrolls" validate constraint "payrolls_processor_id_fkey";

create table "hr"."payroll_entries" (
    "payroll_entry_id" bigint generated by default as identity not null,
    "timesheet_entry_id" bigint,
    "payroll_id" bigint,
    "minutes_paid" integer,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
);


alter table "hr"."payroll_entries" enable row level security;

CREATE UNIQUE INDEX payroll_entries_pkey ON hr.payroll_entries USING btree (payroll_entry_id);

alter table "hr"."payroll_entries" add constraint "payroll_entries_pkey" PRIMARY KEY using index "payroll_entries_pkey";

alter table "hr"."payroll_entries" add constraint "payroll_entries_payroll_id_fkey" FOREIGN KEY (payroll_id) REFERENCES hr.payrolls(payroll_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "hr"."payroll_entries" validate constraint "payroll_entries_payroll_id_fkey";

alter table "hr"."payroll_entries" add constraint "payroll_entries_timesheet_entry_id_fkey" FOREIGN KEY (timesheet_entry_id) REFERENCES hr.timesheet_entries(timesheet_entry_id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "hr"."payroll_entries" validate constraint "payroll_entries_timesheet_entry_id_fkey";